/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package inventory

import kotlin.test.Test
import kotlin.test.assertNotNull

class InventoryAppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = InventoryApp()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
