/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package account

import kotlin.test.Test
import kotlin.test.assertNotNull

class AccountAppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = AccountApp()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
