/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package inventory

import profile.Profile

class InventoryApp {

    val greeting: String
        get() {
            val profile = Profile().getCurrentProfile()
            return "Hi, $profile."
        }
}

fun main(args: Array<String>) {
    println("[inventory-app] ${InventoryApp().greeting}")
}
