/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package profile

import kotlin.test.Test
import kotlin.test.assertNotNull

class ProfileTest {
    @Test fun testGetCurrentProfile() {
        val classUnderTest = Profile()
        assertNotNull(classUnderTest.getCurrentProfile(), "getGreeting should return non-null value")
    }
}
